### ISSUE TITLE
Feature : Create CRUD operations

### ISSUE THREAD

**Issue by ThomasBouasli** [ThomasBouasli/node-api#3]
# Task : Create CRUD operations

The API should have endpoints that enable the user to manipulate the data.

## Pre Requisits

- [ ] The data structure must be defined on #2 
- [ ] The express app should be Functional #1 
- [ ] Nested data should have an exclusive Endpoint
